/* Automatically generated by './build/build-entry.js' */

import ScrollTabs from '../packages/scroll-tabs/index.js';
import FormFactory from '../packages/form-factory/index.js';
import DialogLayout from '../packages/dialog-layout/index.js';

const components = [
  ScrollTabs,
  FormFactory,
  DialogLayout
];

const install = function(Vue, opts = {}) {
  opts;
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$YvVueComponents = {};

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.1.1',
  install,
  ScrollTabs,
  FormFactory,
  DialogLayout
};

