/* Automatically generated by './build/build-entry.js' */

import ScrollTabs from '../packages/scroll-tabs/index.js';

const components = [
  ScrollTabs
];

const install = function(Vue, opts = {}) {
  opts;
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$YvVueComponents = {};

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.0.0',
  install,
  ScrollTabs
};

